version: "3"
services:
  sqler:
    image: dalongrong/sqler:2.0
    volumes:
    - "./config/config-example.hcl:/app/config.example.hcl"
    environment:
    - "DSN=root@tcp(gitbase:3306)/gitbase"
    ports:
    - "3678:3678"
    - "8025:8025"
  gitbase:
    container_name: gitbase
    hostname: gitbase
    image: srcd/gitbase:v0.20.0-rc1
    volumes: 
    - "./git-demos:/opt/repos"
    ports:
    - "3306:3306"